

import type { IntelligenceSnapshot, MasterAIBrainOutput } from '@/intelligence/schemas';

/**
 * The Master AI Brain acts as the final decision-maker. It consumes the fully enriched 
 * Intelligence Snapshot, which includes generated trade scenarios, and produces a final, 
 * actionable decision. It no longer runs sub-engines; it only evaluates the final state.
 */
export async function makeFinalDecision(snapshot: Partial<IntelligenceSnapshot>): Promise<MasterAIBrainOutput | null> {
    const { signalConfidence, riskEnvironment, tradeScenarios } = snapshot;

    // Guard clauses to ensure the pipeline has run correctly before this stage.
    if (!signalConfidence || !riskEnvironment || !tradeScenarios) {
        console.error("[MasterAIBrain] Critical data missing from snapshot. Aborting decision.");
        return {
            status: "NO_SETUP",
            decision: "WAIT",
            confidence: 0,
            commentary: "Master AI Brain aborted due to incomplete intelligence snapshot."
        };
    }

    if (riskEnvironment.tradeMode === 'HALTED') {
        return {
            status: "HALTED",
            decision: "HALT",
            confidence: 1,
            commentary: `Trading is halted due to high-risk environment: ${riskEnvironment.notes}`
        }
    }

    if (tradeScenarios.length === 0) {
        return {
            status: "NO_SETUP",
            decision: "WAIT",
            confidence: 0,
            commentary: "No high-probability trade scenarios were generated by the Strategy Engine."
        };
    }

    // Find the scenario with the highest probability
    const bestScenario = tradeScenarios.reduce((best, current) => (current.probability > best.probability) ? current : best, tradeScenarios[0]);

    // The brain's decision logic: convert scenario probability into a clear action.
    const decision = bestScenario.probability > 0.7 ? "EXECUTE_PRIMARY_SCENARIO" : "MONITOR_SCENARIO";
    const confidence = signalConfidence.finalConfidence;

    return {
        status: "READY",
        decision: decision,
        confidence: confidence,
        commentary: `Primary scenario '${bestScenario.scenario}' has a ${Math.round(bestScenario.probability * 100)}% probability. Confidence in the dominant bias is ${Math.round(confidence * 100)}%.`
    };
}
